// Sirpam 3D Labs Mold — shared inline-style tokens for the control panel steps.
import { colors, radii, spacing, fontSizes, shadows, fonts } from '../../theme';

export const styles = {
  panel: {
    width: 380,
    background: colors.panelBg,
    borderLeft: 'none',
    display: 'flex',
    flexDirection: 'column' as const,
    minHeight: 0,
    fontFamily: fonts.body,
  },
  scrollArea: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: spacing.lg,
    flex: 1,
    overflowY: 'auto' as const,
    padding: spacing.xl,
    paddingTop: spacing.md,
  },
  section: {
    background: colors.sectionBg,
    borderRadius: radii.xl,
    padding: spacing.md + 4,
    border: 'none',
    boxShadow: shadows.raised,
  },
  sectionTitle: {
    fontSize: fontSizes.sm,
    fontWeight: 600,
    color: colors.textDim,
    marginBottom: spacing.sm + 2,
    textTransform: 'uppercase' as const,
    letterSpacing: 1.5,
  },
  sectionHeaderRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.sm + 2,
  },
  button: {
    width: '100%',
    padding: `${spacing.sm + 2}px ${spacing.lg}px`,
    borderRadius: radii.md,
    border: 'none',
    cursor: 'pointer',
    fontWeight: 600,
    fontSize: fontSizes.md,
    transition: 'all 0.15s',
  },
  primaryBtn: {
    background: colors.primary,
    color: '#fff',
    boxShadow: shadows.primary,
    borderRadius: radii.pill,
  },
  secondaryBtn: {
    background: colors.sectionBg,
    color: colors.textBody,
    boxShadow: shadows.raisedSm,
    borderRadius: radii.pill,
  },
  disabledBtn: {
    opacity: 0.5,
    cursor: 'not-allowed' as const,
  },
  axisBtn: (active: boolean) => ({
    flex: 1,
    padding: `${spacing.sm}px ${spacing.md}px`,
    borderRadius: radii.md,
    border: 'none',
    background: colors.sectionBg,
    boxShadow: active ? shadows.inset : shadows.raisedSm,
    color: active ? colors.primary : colors.textMuted,
    cursor: 'pointer',
    fontWeight: 600,
    fontSize: fontSizes.md,
  }),
  slider: { width: '100%' },
  toggleRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: `${spacing.xs + 2}px 0`,
  },
  label: {
    fontSize: fontSizes.sm,
    color: colors.textBody,
  },
  fileInfo: {
    fontSize: fontSizes.sm,
    color: colors.fileInfo,
    wordBreak: 'break-all' as const,
  },
  exportBtn: {
    flex: 1,
    padding: `${spacing.sm}px ${spacing.md}px`,
    borderRadius: radii.md,
    border: 'none',
    background: colors.sectionBg,
    boxShadow: shadows.raisedSm,
    color: colors.textBody,
    cursor: 'pointer',
    fontWeight: 600,
    fontSize: fontSizes.sm,
  },
  resetLinkBtn: {
    background: 'transparent',
    border: 'none',
    color: colors.textDim,
    fontSize: fontSizes.xs,
    cursor: 'pointer',
    padding: 0,
    textDecoration: 'underline',
    fontFamily: 'inherit',
  },
  resetLinkBtnDisabled: {
    opacity: 0.4,
    cursor: 'default' as const,
    textDecoration: 'none' as const,
  },
  statRow: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: 8,
    padding: `4px 0`,
    fontSize: fontSizes.sm,
    color: colors.textDim,
  },
  input: {
    width: '100%',
    padding: `${spacing.xs + 2}px ${spacing.sm}px`,
    borderRadius: radii.sm,
    border: 'none',
    background: colors.viewportBg,
    boxShadow: shadows.inset,
    color: colors.textPrimary,
    fontSize: fontSizes.sm,
    fontFamily: 'inherit',
  },
  select: {
    width: '100%',
    padding: `${spacing.sm}px ${spacing.md}px`,
    borderRadius: radii.sm,
    border: 'none',
    background: colors.viewportBg,
    boxShadow: shadows.inset,
    color: colors.textPrimary,
    fontSize: fontSizes.sm,
    fontFamily: 'inherit',
  },
  hint: {
    fontSize: fontSizes.xs,
    color: colors.textDim,
    lineHeight: 1.4,
  },
};

export { colors, radii, spacing, fontSizes, shadows, fonts };
